### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by Tianqi-Dotes** [scjtqs2/dnf-centos5#1]
请问这个服务端能搭起来玩吗
客户端咋整
是几级的版本 谢谢

**Comment by scjtqs2** [comment]
> 

1、能
2、参考 https://github.com/scjtqs2/dnf-centos5/tree/master/docs
3、自带的95级

**Comment by Tianqi-Dotes** [comment]
谢谢哥 我试试 能不能加个微信594043616
